# Ionic AppFlow 配置文件
# 用于自动化构建和部署

# 构建配置
build:
  # Android 构建配置
  android:
    # 构建前脚本
    pre_build:
      - npm ci
      - npm run build
      - npx cap add android
      - npx cap sync android
      - chmod +x android/gradlew
    
    # 构建命令
    build_command: cd android && ./gradlew assembleDebug
    
    # 构建后脚本
    post_build:
      - echo "Android 构建完成"
    
    # 环境变量
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_HOME: /opt/android-sdk-linux
      
  # iOS 构建配置
  ios:
    pre_build:
      - npm ci
      - npm run build
      - npx cap add ios
      - npx cap sync ios
    
    build_command: npx cap build ios
    
    post_build:
      - echo "iOS 构建完成"

# 部署配置
deploy:
  # 生产环境部署
  production:
    pre_deploy:
      - echo "准备生产部署"
    
    deploy_command: echo "部署到生产环境"
    
    post_deploy:
      - echo "生产部署完成"
